version: "3.9" # Make sure to use a valid version number

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # Vite default port
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Correct volume definition

volumes:
  pgdata: {} # Define the volume for PostgreSQL
  node_modules: {} # Define the volume for the frontend
